spring.application.name=gateway-service

spring.cloud.gateway.routes[0].id=PRODUCT-SERVICE
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/produk/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[1].id=ORDER-SERVICE
spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[2].id=AUTH-SERVICE
spring.cloud.gateway.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

server.port=8082
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
eureka.instance.hostname=${GATEWAY_HOST:localhost}

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
