spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: example_route
          uri: https://example.org
          predicates:
            - Path=/get/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUK
          predicates:
            - Path=api/produk/**
        - id: PELANGGAN-SERVICE
          uri: lb://PELANGGAN
          predicates:
            - Path=api/pelanggan/**
        - id: ORDER-SERVICE
          uri: lb://ORDER
          predicates:
            - Path=api/order/**

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost